### ISSUE TITLE
Setting up a GitHub Action

### ISSUE THREAD

**Issue by ryanfortner** [Jai-JAP/tabby-arm-builds#2]
You can use github actions to automate the compiling and releasing of new tabby versions. For an example, see @hmsjy2017 's xmake workflow: https://github.com/hmsjy2017/xmake-debs/blob/main/.github/workflows/build.yml.

**Comment by ryanfortner** [comment]
I'll try creating an action later today.

**Comment by Jai-JAP** [comment]
Any updates

**Comment by ryanfortner** [comment]
No, I forgot about this to be honest. I'm putting it on my to-do list

**Comment by Jai-JAP** [comment]
> No, I forgot about this to be honest. I'm putting it on my to-do list

I created an github action can you check that

**Comment by Jai-JAP** [comment]
The GitHub are set up and working as intended
