### ISSUE TITLE
Armv7l builds disappeared

### ISSUE THREAD

**Issue by Botspot** [Jai-JAP/tabby-arm-builds#3]
The past two releases, [this one](https://github.com/Jai-JAP/tabby-arm-builds/releases/tag/v1.0.176) and [this one](https://github.com/Jai-JAP/tabby-arm-builds/releases/tag/v1.0.175), don't contain any `[linux-armv7l.deb](https://github.com/Jai-JAP/tabby-arm-builds/releases/download/v1.0.176/tabby-1.0.176-linux-armv7l.deb)` files. Did you drop support for armv7l, or did something else go wrong?

**Comment by Jai-JAP** [comment]
I have noticed this issue earlier and I am trying to fix it
This issue has appeared when i was setting up a CI for automated builds

**Comment by Jai-JAP** [comment]
Armv7l builds are now armhf builds and up in the releases fixed
