### ISSUE TITLE
upstream tabby upgraded to electron 18.2.4

### ISSUE THREAD

**Issue by theofficialgman** [Jai-JAP/tabby-arm-builds#4]
you can remove the sed from https://github.com/Jai-JAP/tabby-arm-builds/blob/main/.github/workflows/build.yml now that upstream has upgraded so that when version 178 releases this will now use the same electron version as upstream

**Comment by Jai-JAP** [comment]
Done.
Also removed the scripts/build-native.js as it is in postinstall command. See https://github.com/Eugeny/tabby/blob/c80ad41521900f3edb47b2f4046ad679704b7056/package.json#L105

**Comment by theofficialgman** [comment]
@Jai-JAP please add it back, you do NOT run postinstall. executing build-linux.js just executes that, it does not run postinstall.
you do not run postinstall anywhere in your actions https://github.com/Jai-JAP/tabby-arm-builds/blob/main/.github/workflows/build.yml

idk why upstream removed it from their github actions... what they say doesn't work. either add postinstall or just specify build-native.js, your chioce
